### ISSUE TITLE
this isn't working for me :(

### ISSUE THREAD

**Issue by emilyanncr** [fenhl/isup#2]
This used to work for me like a charm, now it's not :(  I know there's a newer script for python3 but that one has never worked for me.  
Traceback (most recent call last):
  File "isup.py", line 13, in <module>
    print "\n".join(isup(d) for d in sys.argv[1:])
  File "isup.py", line 13, in <genexpr>
    print "\n".join(isup(d) for d in sys.argv[1:])
  File "isup.py", line 7, in isup
    resp = urlopen("http://www.isup.me/%s" % domain).read()
  File "/usr/lib/python2.7/urllib.py", line 87, in urlopen
    return opener.open(url)
  File "/usr/lib/python2.7/urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "/usr/lib/python2.7/urllib.py", line 350, in open_http
    h.endheaders(data)
  File "/usr/lib/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 882, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 844, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 821, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
IOError: [Errno socket error] [Errno -2] Name or service not known

**Comment by fenhl** [comment]
You seem to be running Python 2. This script is for Python 3 only.
